version: '2'

services:

  mgmt-ui:
    image: portainer/portainer
    restart: always
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
    expose:
      - 9000
    ports:
      - 80:9000
    deploy:
      placement:
        constraints:
          - node.role == manager

#  openvpn:
#    cap_add:
#     - NET_ADMIN
  # Image to use for Intel based systems
  # image: kylemanna/openvpn
#    image: container4armhf/armhf-docker-openvpn
##    container_name: openvpn
#    ports:
#     - "1194:1194/udp"
#    restart: always
#    volumes:
#     - ./openvpn-data/conf:/etc/openvpn


#  drone-server:
#    image: drone/drone:latest
#    ports:
#      - 8000:8000
#    volumes:
#      - /var/lib/drone:/var/lib/drone/
#    restart: always
#    environment:
#      - DRONE_OPEN=true
#      - DRONE_HOST=${DRONE_HOST}
#      - DRONE_ORGS=ppouliot,interoperable
#      - DRONE_ADMIN=ppouliot
#      - DRONE_GITHUB=true
#      - DRONE_GITHUB_CLIENT=${DRONE_GITHUB_CLIENT}
#      - DRONE_GITHUB_SECRET=${DRONE_GITHUB_SECRET}
#      - DRONE_SECRET=${DRONE_SECRET}

#  drone-agent:
#    image: drone/drone:0.7
#    command: agent
#    restart: always
#    depends_on:
#      - drone-server
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock
#    environment:
#      - DRONE_SERVER=ws://drone-server:8000/ws/broker
#      - DRONE_SECRET=${DRONE_SECRET}

  gogs-mysql-db:
    image: mysql
    container_name: gogs-mysql-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: "gogsdb"
      MYSQL_USER: "gogs"
      MYSQL_PASSWORD: "gogs"
      MYSQL_ROOT_PASSWORD: "g0g$"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - mysql-data:/var/lib/mysql

  gogs:
    image: gogs/gogs:latest
    restart: always
    ports:
      - "10022:22"
      - "3000:3000"
    links:
      - gogs-mysql-db
    environment:
      - "RUN_CROND=true"
    networks:
      - gogs
    volumes:
      - "gogs-data:/data"
    depends_on:
      - gogs-mysql-db

#networks:
#    gogs:
#      driver: bridge

volumes:
    openvpn-data:
      driver: local
    mysql-data:
      driver: local
    gogs-data:
      driver: local
